apiVersion: v1
data:
  prometheus.yaml: "Z2xvYmFsOgogIHNjcmFwZV9pbnRlcnZhbDogMTBzCiAgc2NyYXBlX3RpbWVvdXQ6IDEwcwogIGV2YWx1YXRpb25faW50ZXJ2YWw6IDEwcwo="
kind: Secret
metadata:
  name: prometheus-conifig-tke-1
  namespace: monitoring
type: Opaque
